name: Publish Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
