name: Publish Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - name: Setup uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    - name: Deploy docs
      run: uv run mkdocs gh-deploy --force
